server:
  port: 8030


spring:
  data:
    redis:
      port: 6379
      host: 10.33.93.12

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.33.93.12:3306/x?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

  kafka:
    bootstrap-servers: 10.33.93.12:9092

logging:
  level:
    com.x.data.sync.service: info

kafka:
  bootstrap-servers: 10.33.93.12:9092 # Kafka集群地址
  consumer:
    group-id: data-sync-group # 消费组ID
    topic: test-topic # 消费主题
    batch-size: 1024 # 每次poll最大消息数
    fetch-min-size: 10240 # 拉取最小字节数（10KB）
    fetch-max-wait-ms: 500 # 拉取最大等待时间（500ms）
    concurrency: 3 # 并发消费者数量（建议≤分区数）
    write-batch-size: 1024 # 每批写入IotDB的最大条数
    auto-offset-reset: latest # 偏移量重置策略
    enable-auto-commit: false # 关闭自动提交

iotdb:
  nodeUrls: 10.33.93.12:6667
  username: root
  password: root

# Dubbo配置
dubbo:
  consumer:
    check: false # 禁用启动检测
    lazy: true   # 全局延迟注入，避免时机冲突
  application:
    name: ${spring.application.name}
    logger: slf4j
    qos-enable: false # 可选，默认true, QOS 服务治理功能
  registry:
    address: nacos://nacos:nacos@10.33.93.12:8848
    register-mode: instance
  protocols:
    tri-id:
      name: tri
      port: -1