server:
  port: 9001

spring:
  application:
    name: x-tcp-gateway-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        
  config:
    import:
      - optional:nacos:application-${spring.profiles.active}.yml
      - optional:nacos:application.yml

logging:
  level:
    com.x: debug