server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.33.93.12:13306/x_manage?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    
# Dubbo配置
dubbo:
  application:
    name: ${spring.application.name}
  registry:
    address: nacos://nacos:nacos@10.33.93.12:8848
  protocol:
    name: grpc
    port: -1

logging:
  level:
    com.x.manage.service: debug